name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: panggilrofan/.github/.github/workflows/ci-module.yml@master
    with:
      min-node-version: 14
